spring.application.name=lo10-devops-lab

# Cho phép thay đổi cổng bằng biến môi trường.
server.port=${SERVER_PORT:8080}

# Public các Actuator endpoint cần thiết.
management.endpoints.web.exposure.include=health,info

# Hiển thị chi tiết trạng thái health.
management.endpoint.health.show-details=always

# Bật liveness và readiness probes.
management.endpoint.health.probes.enabled=true

# Cho phép ứng dụng dừng an toàn.
server.shutdown=graceful

# Thời gian chờ request hiện tại hoàn tất khi shutdown.
spring.lifecycle.timeout-per-shutdown-phase=20s

# Thông tin ứng dụng qua Actuator.
info.app.name=${spring.application.name}
info.app.description=LO10 DevOps Lab for Docker, CI/CD and Structured Logging
info.app.version=0.0.1-SNAPSHOT
info.app.java-version=21

# Xuất log Console dưới dạng JSON theo Logstash format.
logging.structured.format.console=logstash

# Log level của source code trong project.
logging.level.com.thongtv5.lo10devopslab=INFO